### PR TITLE
Vagrant setup

### PR DESCRIPTION
**Pull request by ChiragGhanshani**

### CODE REVIEW

**Comment by zmughal** [comment]
Looks good, go ahead and merge

**Comment by zmughal** [comment]
@ChiragGhanshani, please squash https://github.com/project-renard/devops/pull/7/commits/c984c78636f90355852d4a4526665e58cad45f39 on to https://github.com/project-renard/devops/pull/7/commits/f35fb097a172fd49e159035d0035d261db1910c5 and edit the commit message to remove the reference to the box name.

@StayerX, what do you think?

**Comment by ChiragGhanshani** [comment]
Hmm, I think I squashed into the wrong commit

**Comment by zmughal** [comment]
No problem, do

``` shell
git reset --hard c984c78636f90355852d4a4526665e58cad45f39
```

and get the previous state. When you do the squash, make sure you move the line referring to c984c78 below f35fb09.

**Comment by StayerX** [comment]
based on what I am seeing right now I approve.

**Comment by ChiragGhanshani** [comment]
@zmughal how's this?

**Comment by zmughal** [comment]
Could you edit out "set box to debian/config-jessie64" in the commit message of https://github.com/project-renard/devops/pull/7/commits/d50301dfe1d81c4a4e8a5277bdb3a82512481af5 when you rebase interactively? After that, the code looks good to merge.

**Comment by zmughal** [comment]
Looks good to merge! Merging!

**Pull request merged**
